disabled_rules:
  - trailing_newline
  - trailing_whitespace
  - line_length
  - colon
  - comma

opt_in_rules:
  - empty_count
  - force_cast
  - force_try
  - leading_whitespace
  - function_body_length
  - function_parameter_count
  - legacy_constant
  - operator_whitespace
  - return_arrow_whitespace
  - todo
  - nesting

cyclomatic_complexity:
  - 15
  - 20

variable_name:
  excluded:
    - id
    - URLEscapedString
    - MeetupAPIProvider
    - MeetupAPIConsumer

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - CocoaHeadsAppIntegrationTests
  - CocoaHeadsAppTests
  - CocoaHeadsAppUITests
  - CocoaHeadsApp/R.generated.swift
