def common_pods
    pod 'R.swift', '~> 1.3.0'
    pod 'Unbox', '1.0'
    pod 'Moya', '~> 6.1.3'
    pod 'XCGLogger', '~> 3.2'
    pod 'Nuke', '~> 2.0.1'
    pod 'CPDAcknowledgements', '~> 1.0'
    pod 'DynamicColor', '~> 2.4.0'
end

def common_test_pods
    pod 'OHHTTPStubs', '~> 4.7.0'
    pod 'OHHTTPStubs/Swift'
end

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

xcodeproj 'CocoaHeadsApp.xcodeproj'

common_pods

target :CocoaHeadsAppTests do
    xcodeproj 'CocoaHeadsApp.xcodeproj'
    common_pods
end

target :CocoaHeadsAppIntegrationTests do
    xcodeproj 'CocoaHeadsApp.xcodeproj'
    common_pods
    common_test_pods
end

target :CocoaHeadsAppUITests do
    xcodeproj 'CocoaHeadsApp.xcodeproj'
    common_pods
    common_test_pods
end

post_install do |installer|
    plugin 'cocoapods-acknowledgements', :settings_bundle => true

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_TESTABILITY'] = 'YES'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
