plugin 'cocoapods-keys', {
  :project => 'CocoaHeadsApp',
  :keys => [
    'ParseApplicationId',
    'ParseClientKey'
  ]
}

platform :ios, '8.0'
use_frameworks!

pod 'R.swift'
pod 'Unbox', '1.0'
pod 'Moya'
pod 'XCGLogger'
pod 'Nuke'
pod 'Parse'
